@startuml
actor User

activate UI
User -> UI : Enters "edit-patient INDEX [fields]"
UI -> LogicManager : execute("edit-patient INDEX [fields]")

activate LogicManager
LogicManager -> AddressBookParser : parseCommand("edit-patient INDEX [fields]")
activate AddressBookParser
AddressBookParser -> EditPatientCommand: new()
activate EditPatientCommand
EditPatientCommand --> AddressBookParser
deactivate EditPatientCommand
AddressBookParser-->LogicManager
deactivate AddressBookParser

LogicManager -> Model : execute(EditPatientCommand)

activate Model
Model -> AddressBook : editPatient
activate AddressBook
AddressBook --> Model : updatedAddressBook
deactivate AddressBook
Model-->LogicManager : updatedAddressBook
deactivate Model

LogicManager -> Storage : save(updatedAddressBook)
activate Storage
Storage --> LogicManager
deactivate Storage

LogicManager --> UI : CommandResult("Edited entity successfully")
deactivate LogicManager

UI -> UI : refresh()
@enduml
